import type { VercelRequest, VercelResponse } from '@vercel/node';
import nodemailer from 'nodemailer';

// Helper to format values elegantly in HTML
const formatLabel = (key: string) => {
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (str) => str.toUpperCase());
};

// Mithila styling configuration
const BRAND_COLORS = {
  primary: '#1c1917', // Stone-900 (charcoal)
  secondary: '#fefcbf', // Yellow-100 (subtle gold tint)
  accent: '#ca8a04', // Yellow-600 (mithila gold/mustard)
  textDark: '#292524', // Stone-800
  textLight: '#78716c', // Stone-500
  bgLight: '#fafaf9', // Stone-50 (warm cream)
  white: '#ffffff',
  border: '#e7e5e4', // Stone-200
};

// Elegant HTML wrapper template
const getHtmlWrapper = (title: string, contentHtml: string, isConfirmation: boolean) => {
  const greeting = isConfirmation 
    ? `<div style="padding: 24px 32px 0 32px; font-family: 'Playfair Display', Georgia, serif;">
        <h2 style="color: ${BRAND_COLORS.primary}; font-size: 20px; font-weight: 500; margin: 0;">Namaste,</h2>
        <p style="color: ${BRAND_COLORS.textDark}; font-size: 15px; line-height: 1.6; margin-top: 8px; margin-bottom: 0;">
          Thank you for choosing Janakpur Inn. We have successfully received your request! Below are the details of your submission:
        </p>
       </div>`
    : `<div style="padding: 24px 32px 0 32px;">
        <h2 style="color: ${BRAND_COLORS.primary}; font-size: 20px; font-weight: 600; margin: 0;">Administrative Alert</h2>
        <p style="color: ${BRAND_COLORS.textDark}; font-size: 15px; margin-top: 8px; margin-bottom: 0;">
          A new inquiry has been submitted through the Janakpur Inn website. Please see the details below:
        </p>
       </div>`;

  const footerText = isConfirmation
    ? `<p style="margin: 0; margin-bottom: 8px;">We look forward to welcoming you to the gateway of heritage and hospitality.</p>
       <p style="margin: 0; font-weight: 600;">Janakpur Inn Team</p>`
    : `<p style="margin: 0;">This email was automatically generated by the Janakpur Inn Website system.</p>`;

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${title}</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f5f5f4; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased;">
      <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: #f5f5f4; padding: 32px 16px;">
        <tr>
          <td align="center">
            <!-- Main Card Container -->
            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px; background-color: ${BRAND_COLORS.white}; border-radius: 12px; overflow: hidden; border: 1px solid ${BRAND_COLORS.border}; box-shadow: 0 4px 12px rgba(28, 25, 23, 0.04);">
              
              <!-- Branded Header -->
              <tr>
                <td style="background-color: ${BRAND_COLORS.primary}; padding: 32px; text-align: center; border-bottom: 4px solid ${BRAND_COLORS.accent};">
                  <h1 style="color: ${BRAND_COLORS.white}; font-family: 'Playfair Display', Georgia, serif; font-size: 26px; font-weight: 300; letter-spacing: 2px; margin: 0; text-transform: uppercase;">
                    Janakpur Inn
                  </h1>
                  <p style="color: ${BRAND_COLORS.accent}; font-size: 11px; letter-spacing: 3px; margin: 6px 0 0 0; text-transform: uppercase; font-weight: 600;">
                    Hotel & Restaurant
                  </p>
                </td>
              </tr>

              <!-- Warm Greeting -->
              <tr>
                <td>${greeting}</td>
              </tr>

              <!-- Detailed Grid Content -->
              <tr>
                <td style="padding: 24px 32px;">
                  <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: ${BRAND_COLORS.bgLight}; border-radius: 8px; border: 1px solid ${BRAND_COLORS.border}; overflow: hidden;">
                    ${contentHtml}
                  </table>
                </td>
              </tr>

              <!-- Signoff / Instructions -->
              <tr>
                <td style="padding: 0 32px 32px 32px; font-size: 14px; color: ${BRAND_COLORS.textDark}; line-height: 1.6; border-bottom: 1px solid ${BRAND_COLORS.border};">
                  ${footerText}
                </td>
              </tr>

              <!-- Address Footer -->
              <tr>
                <td style="padding: 32px; background-color: #fafaf9; text-align: center; font-size: 12px; color: ${BRAND_COLORS.textLight}; line-height: 1.8;">
                  <p style="margin: 0; font-weight: 600; color: ${BRAND_COLORS.textDark}; font-size: 13px; margin-bottom: 6px;">Hotel Janakpur Inn</p>
                  <p style="margin: 0;">Ramanand Chowk, Janakpur Dham - 08, Nepal</p>
                  <p style="margin: 0;">Phones: +977 9810685891, +977 41-591317, +977 41-591989, +977 9765263291</p>
                  <p style="margin: 6px 0 0 0;">Email: <a href="mailto:janakpurinnhna2079@gmail.com" style="color: ${BRAND_COLORS.accent}; text-decoration: none;">janakpurinnhna2079@gmail.com</a></p>
                </td>
              </tr>

            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `;
};

// Generates individual data rows for the email template
const generateRow = (label: string, value: any) => {
  if (value === undefined || value === null || value === '') return '';
  return `
    <tr style="border-bottom: 1px solid ${BRAND_COLORS.border};">
      <td style="padding: 12px 16px; font-size: 13px; font-weight: 600; color: ${BRAND_COLORS.textLight}; width: 35%; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid ${BRAND_COLORS.border};">
        ${label}
      </td>
      <td style="padding: 12px 16px; font-size: 14px; color: ${BRAND_COLORS.textDark}; font-weight: 500; border-bottom: 1px solid ${BRAND_COLORS.border};">
        ${String(value)}
      </td>
    </tr>
  `;
};

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { type, name, email, phone, ...payload } = req.body;

  if (!type || !name || !phone) {
    return res.status(400).json({ error: 'Required fields are missing' });
  }

  // Retrieve environment variables securely
  const {
    SMTP_HOST,
    SMTP_PORT,
    SMTP_SECURE,
    SMTP_USER,
    SMTP_PASS,
    EMAIL_USER,
    OWNER_EMAIL,
    ADMIN_EMAIL,
  } = process.env;

  if (!SMTP_HOST || !SMTP_PORT || !SMTP_USER || !SMTP_PASS) {
    console.error('SMTP configuration environment variables are missing!');
    return res.status(500).json({ error: 'Mail server configuration missing' });
  }

  const ownerAddress = OWNER_EMAIL || ADMIN_EMAIL || 'sat4931@gmail.com';
  const senderAddress = EMAIL_USER || SMTP_USER;

  // Initialize secure transporter
  const transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: parseInt(SMTP_PORT, 10),
    secure: SMTP_SECURE === 'true',
    auth: {
      user: SMTP_USER,
      pass: SMTP_PASS,
    },
  });

  try {
    let emailSubject = '';
    let detailsHtml = '';
    let formTitle = '';

    // Generate specific templates based on submission type
    if (type === 'contact') {
      formTitle = 'Contact Us Message';
      emailSubject = `[Contact Us] ${payload.subject || 'New Inquiry'} - ${name}`;
      detailsHtml = `
        ${generateRow('Submission Type', 'General Inquiry')}
        ${generateRow('Full Name', name)}
        ${generateRow('Email Address', email)}
        ${generateRow('Phone Number', phone)}
        ${generateRow('Subject', payload.subject)}
        ${generateRow('Message', payload.message)}
      `;
    } else if (type === 'restaurant') {
      formTitle = 'Restaurant Reservation';
      emailSubject = `[Restaurant Reservation] ${name} - ${payload.guests} guests`;
      detailsHtml = `
        ${generateRow('Submission Type', 'Restaurant Table Booking')}
        ${generateRow('Guest Name', name)}
        ${generateRow('Email Address', email)}
        ${generateRow('Phone Number', phone)}
        ${generateRow('Date', payload.date)}
        ${generateRow('Time', payload.time)}
        ${generateRow('Number of Guests', payload.guests)}
        ${generateRow('Special Requests', payload.specialRequests)}
      `;
    } else if (type === 'hall') {
      formTitle = 'Event Hall Inquiry';
      emailSubject = `[Hall Inquiry] ${payload.hallName} - ${name}`;
      detailsHtml = `
        ${generateRow('Submission Type', 'Event Hall Booking Request')}
        ${generateRow('Venue/Hall', payload.hallName)}
        ${generateRow('Client Name', name)}
        ${generateRow('Email Address', email)}
        ${generateRow('Phone Number', phone)}
        ${generateRow('Event Date', payload.date)}
        ${generateRow('Estimated Guests', payload.guests)}
        ${generateRow('Event Type', payload.eventType)}
      `;
    } else if (type === 'booking') {
      formTitle = 'Room Booking';
      emailSubject = `[Room Booking] ${name} (${payload.checkIn} to ${payload.checkOut})`;
      const roomsHtml = (payload.roomsFormatted || '').replace(/\n/g, '<br/>');
      detailsHtml = `
        ${generateRow('Submission Type', 'Room Stay Booking')}
        ${generateRow('Booking Ref', payload.bookingReference)}
        ${generateRow('Guest Name', name)}
        ${generateRow('Email Address', email)}
        ${generateRow('Phone Number', phone)}
        ${generateRow('Check-In Date', payload.checkIn)}
        ${generateRow('Check-Out Date', payload.checkOut)}
        ${generateRow('Nights Count', payload.nights)}
        ${generateRow('Rooms Booked', roomsHtml)}
        ${generateRow('Payment Method', payload.paymentMethod)}
        ${generateRow('Special Requests', payload.specialRequests)}
        ${generateRow('Total Cost', `NPR ${payload.total}`)}
      `;
    } else {
      return res.status(400).json({ error: 'Invalid inquiry type' });
    }

    // Build the beautiful templates
    const ownerEmailHtml = getHtmlWrapper(emailSubject, detailsHtml, false);
    const customerEmailHtml = getHtmlWrapper(`Inquiry Confirmed: ${formTitle} - Janakpur Inn`, detailsHtml, true);

    // 1. Send Alert Email to Owner
    await transporter.sendMail({
      from: `"Janakpur Inn Website" <${senderAddress}>`,
      to: ownerAddress,
      replyTo: email || undefined,
      subject: emailSubject,
      html: ownerEmailHtml,
    });

    // 2. Send reassurance confirmation email to Customer (if email is provided)
    if (email && email.trim() !== '') {
      await transporter.sendMail({
        from: `"Janakpur Inn" <${senderAddress}>`,
        to: email,
        subject: `Inquiry Received: ${formTitle} at Janakpur Inn`,
        html: customerEmailHtml,
      });
      console.log(`Confirmation email sent successfully to customer: ${email}`);
    }

    return res.status(200).json({ success: true, message: 'Inquiry submitted and emails sent successfully!' });
  } catch (error: any) {
    console.error('Nodemailer error caught:', error);
    return res.status(500).json({ error: 'Failed to process inquiry email', details: error.message });
  }
}
